### ISSUE TITLE
"Quick start" vm - hostmanager doesn't work

### ISSUE THREAD

**Issue by marek-obuchowicz** [spryker/devvm#11]
Related to https://github.com/devopsgroup-io/vagrant-hostmanager/issues/182
At the moment the only possible fix I see is to manually edit `Vagrantfile` after `vagrant init ...`

**Comment by webceyhan** [comment]
I have the same issue, all plugins can be configured in include/Vagrantfile but vagrant-hostmanager.

As a workaround, i created 2 vagrant files.
One is include/Vagrantfile, which contains all settings to configure the basebox as usual, 
and other one contains only "vagrant-hostmanager = enabled" which i use to replace the original Vagrantfile in current project folder before the first vagrant up.

But it is serious problem and really needs to be fixed ASAP..

**Comment by marek-obuchowicz** [comment]
@webceyhan please "+1" the upstream issue (vagrant-hostmanager#182) as we aren't able to fix it on our own - we can just workaround it, like you did

**Comment by hhebbo** [comment]
fixed
