### ISSUE TITLE
NFS should be existing in client machine

### ISSUE THREAD

**Issue by hhebbo** [spryker/devvm#14]
NFS doesn't exist in the client machine causes a problem before ```vagrant up```

we solved like this:
1) Check for existing NFS
dpkg -l | grep nfs-kernel-server
2) If not, install:
apt-get install nfs-kernel-server
apt-get install nfs-common

**Comment by marek-obuchowicz** [comment]
Thanks for the tip, added documentation snippet with install commands (for rh/debian-based linuxes). Running those commands again, if `nfsd` is already installed, doesn't change anything - so i removed the part with `dpkg -l` for checking to keep it simplier.
