### ISSUE TITLE
Xdebug should be installed AND enabled by default for local dev

### ISSUE THREAD

**Issue by dereuromark** [spryker/devvm#16]
It is not a good idea to ship the default developer boxes without proper debugging.
It is also time consuming and too complicated right now to set it up.

On Linux Ubuntu I on top got these errors:
```
The following NEW packages will be installed:
  php5-xdebug
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
Need to get 0 B/242 kB of archives.
After this operation, 927 kB of additional disk space will be used.
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)
```

**Comment by dereuromark** [comment]
Also, even MORE important is proper default handling regarding error display
See https://github.com/spryker/spryker/issues/1689

Basically, the developers local machine MUST display errors by default.
Cloaking them with a simple white page and no details is not acceptable as default.
Right now it seems we are using the same vagrant machine as if it was the "live production server env", which it is not.
If there is no way to make this switch, then there must be documentation regarding how to quickly enable error logging and display

    ini_set('display_errors','On');

So this INI setting should be on by default inside a fresh vagrant machine, along with xdebug enabled - or there must be a very simple way of doing this in < 1 min when setting up the machine (vagrant init?).

**Comment by dereuromark** [comment]
One idea could be to have a

    production/live: 0/1

switch (default 1!) to quickly change the virtual box to a live one. Live = no xdebug and no error display.

**Comment by marek-obuchowicz** [comment]
We have a condition in php-fpm configs to set `display_errors=off` on production only. However the default entry in `php.ini` was also `display_errors=off` so we had it globally disabled. Fix will be released in new build of VM.

**Comment by hhebbo** [comment]
this is already done
