### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by Sam-Burns** [spryker/devvm#18]
Would you consider adding a `LICENSE` file to the root of repository, to clarify the licensing situation?  Some of your other repos are published under the MIT license - was that the intention here?

**Comment by marek-obuchowicz** [comment]
Technically we can create any LICENSE file while executing `vagrant up`, is there any license to be applied here? We have here some code in `Vagrantfile`.

**Comment by hhebbo** [comment]
@Sam-Burns what root repository do you mean? Can you give an example please?

**Comment by marek-obuchowicz** [comment]
Please include more feedback if this is still relevant. At the moment closing issue as it's not clear what to do. Will reopen if needed.
