### ISSUE TITLE
console kills/resets the current dir

### ISSUE THREAD

**Issue by dereuromark** [spryker/devvm#20]
The documentation right now always says ( http://spryker.github.io/core/bundles/collector/ ):

    console collector:search:export

People take that literally (instead of `vendor/bin/console ...`) and then it resets their current dir to the root one (or in my case for some reason into vendor dir).
So they have to `cd ...` back into it.

The alias should be fixed to keep the dir. Or we need to modify the docs to always use full path.

**Comment by hhebbo** [comment]
moved to jira
