### ISSUE TITLE
webpack hangs

### ISSUE THREAD

**Issue by Detzler** [spryker/devvm#21]
Execution of "antelope build" hangs at the point "building assets using webpack".
It's just idling, nothing happens.

I've found some resources about "webpack hangs". But couldn't fix it in the vm. Could you help, please?

Using Mac.

**Comment by abelspry** [comment]
Hi @Detzler,
sorry for the superlate answer.

We created a new antelope version (now is 2.2.0) that should solve this problem. If it persists, please open a new ticket here:
https://github.com/spryker/antelope/issues

Cheers.
Alessandro
