### ISSUE TITLE
Enable sending mails from VM

### ISSUE THREAD

**Issue by the-colorant** [spryker/devvm#22]
From @stereomon 

Currently we cannot test mails locally. We have only Mandrill as Provider were we dont have any credentials right now.

We could do different things to make it testable locally
- Add PersistenceProvider to persist the data given from the MailTransfer and check if all data we expect is persisted (#1480 (comment))
- Use SwiftMailer to send mails with gmail and provide some basic template others could use to start with

**Comment by lmanzke** [comment]
At lumas we use a file system mailer that stores the variables to be sent to a json file. (Note however that not the whole e-mail content is persisted because the templates are inside of the mandrill account). A similar implementation could be used in the core.

**Comment by hhebbo** [comment]
moved to jira
