### ISSUE TITLE
Requirements for DevVM

### ISSUE THREAD

**Issue by hhebbo** [spryker/devvm#23]
- [x] Add Mark and Rene with full access to the Toran sever, so they can work on it directly. And build a concept for adding new release managers to the Toran server.
- [x] Rotate logs for the Subsplit app, otherwise the server crashes soon
- [ ] Have two DevVMs in the same machine; one for project (no split) and one for demoshop (with split). Each DevVM has its own IP, hosts, and name
- [ ] Allow some test environment separated from the main one.
- [x] Make cloning from the split public, Pawel started working on that, and we don’t know the state
- [x] `.dev` is an official domain now, need to change that for our development to `.local`
- [ ] ELK in the VM (Please talk to René)

**Comment by marek-obuchowicz** [comment]
Regarding `Release app to be included in the saltstack` and after feedback from @dereuromark:
 - release app is not open source, so we don't directly include it in saltstack (which is opensource)
 - additional configuration is needed per-user (github token, e-mail, jira credentials) -> full automated setup is not feasible

Therefore proposed solution: don't run it from dev vm (release-app doesn't depend on the vm), run it as docker container (easy and quick to setup). Proposing solution via PR of release-app.

**Comment by dereuromark** [comment]
- [ ] ElasticSearch 2.* should also at some point become a requirement. To be discussed with fabian, as it is not BC.

**Comment by hhebbo** [comment]
moved these as separated tickets to Jira
