### ISSUE TITLE
Build error on devvm while installation

### ISSUE THREAD

**Issue by diabolus** [spryker/devvm#30]
I tried to make a fresh install and flow the guidelines but when i ran the install script installation failed and got this error below;

YVES
DEFAULT theme
- collecting data...
  ┗ entry points: 4 valid | 0 duplicates | 4 total
  ┗ configuration: ./assets/Automation/yves-default.antelope.js
- building assets using webpack...
  ┗ ModuleBuildError: Module build failed:
  $rgba: red($color), green($color), blue($color);
        ^
      Argument `$color` of `red($color)` must be a color

Backtrace:
	node_modules/foundation-sites/scss/util/_color.scss:19, in function `red`
	node_modules/foundation-sites/scss/util/_color.scss:19, in function `color-luminance`
	node_modules/foundation-sites/scss/util/_color.scss:44, in function `color-contrast`
	node_modules/foundation-sites/scss/util/_color.scss:63, in function `color-pick-contrast`
	node_modules/foundation-sites/scss/components/_badge.scss:59, in mixin `foundation-badge`
	stdin:20
      in /data/shop/development/current/node_modules/foundation-sites/scss/util/_color.scss (line 19, column 10)

[!] Automation error: execution aborted (err: automation)
    Something went wrong during automation process
    Error: CompilationError
    Trace info: assets compilation,compilation report

Tool executed in 15.274 seconds | Exit code: 3

=> Antelope build failed <=

**Comment by dereuromark** [comment]
Please see the following changes to your demoshop package.json file:
https://github.com/spryker/demoshop/commit/ce20dc9e7a04c3ed41d0174c6e317909d0b40808#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L12
That should resolve your issue.
