### ISSUE TITLE
Update VM node.js to version 8.x

### ISSUE THREAD

**Issue by abelspry** [spryker/devvm#43]
To enforce the stability and increase the deployment speed, the node.js version on the VM should be, by default, version 8.x. 

Version 8 is going to be LTS by 2017-10-31 according to nodejs repo:
https://github.com/nodejs/Release

**Comment by marek-obuchowicz** [comment]
@abelspry is this still relevant, when we have nvm installed?

**Comment by abelspry** [comment]
Nope, definitely. Thanks.
