### ISSUE TITLE
Add NVM to the VM

### ISSUE THREAD

**Issue by abelspry** [spryker/devvm#44]
Add NVM to the VM.
https://github.com/creationix/nvm

NVM automatically manages nodejs versions by downloading and installing them for a specific folder (and subfolders) by refering to a `.nvmrc` file. This brings great flexibility about which version to use, aligns all the developers to the same version and allows multiple versions on the same project (if and when needed).

**Comment by marek-obuchowicz** [comment]
@abelspry as it was added to dev vm v1.0.2, can you please confirm that we can close this issue?

**Comment by abelspry** [comment]
yep
