### ISSUE TITLE
2.x: Less confusing name for project

### ISSUE THREAD

**Issue by dereuromark** [spryker/devvm#47]
In sync with `VM_PROJECT =         'project'`:

I would still recommend fixing the two options
```
SPRYKER_BRANCH =     'master'
SPRYKER_REPOSITORY = 'git@github.com:spryker/project.git'
```
to what they actually are:
```
VM_PROJECT_BRANCH
VM_PROJECT_REPOSITORY
```
(or without the VM_prefix)

**Comment by dereuromark** [comment]
PROJECT_BRANCH and PROJECT_REPOSITORY should be short enough / fine.

**Comment by marek-obuchowicz** [comment]
Duplicate of internal ticket - VM-18
