### ISSUE TITLE
consider supporting LXC next to virtualbox

### ISSUE THREAD

**Issue by lsmith77** [spryker/devvm#51]
This gives much better performance on Linux hosts. This would make it also feasible to run the VM in CI setups.

**Comment by marek-obuchowicz** [comment]
@lsmith77 won't be implemented in short future, as the dev vm is an example can can be customized to project needs. We have decided to include the common setup that works for most users (linux, mac, windows) and will stick to that.
If you would like to implement it yourself and share the implementation, feel free to open a pull request.

**Comment by marek-obuchowicz** [comment]
Closing it now, as the team is focusing at the moment on delivery of docker-based solution, which will run on Linux with native performance and will offer lots of flexibility for automated CI/CD setups.
