### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

### ISSUE THREAD

**Issue by Prizzler** [spryker/devvm#54]
Hi,

i tried to install spryker today and got this error msg:

```console
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'devvm2.0.0' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'devvm2.0.0' (v0) for provider: virtualbox
    default: Downloading: https://github.com/spryker/devvm/releases/download/v2.0.0/spryker-devvm.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
```

i know this is not an issue of spryker. In case you have the same error you can add the spryker box with the insecure-flag of vagrant like that:

```console
vagrant box add --insecure -c devvm2.0.0 https://github.com/spryker/devvm/releases/download/v2.0.0/spryker-devvm.box
```

**Comment by marek-obuchowicz** [comment]
Does this issue still happen, or was it a temporary glitch? As you pointed out, it's not related to Spryker - SSL certificate validation for github.com failed, which seems strange to me...

**Comment by Prizzler** [comment]
today I did a new installation on my new workstation with a current version of vagrant (2.1.1) and vbox (5.2.12). everything worked as expected, with no errors. I think my problem was the outdated vagrant
version 2.0.1 on my previous workstation.

**Comment by marek-obuchowicz** [comment]
Thanks for feedback!
