### ISSUE TITLE
Installation fails on MacOS Mojave due to enabled SIP

### ISSUE THREAD

**Issue by caspahouzer** [spryker/devvm#59]
With SIP enabled, the installation stucks on `Mounting NFS shared folders...`

A possible solution is to disable SIP: https://github.com/hashicorp/vagrant/issues/10234#issuecomment-424281688

How to disable: https://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/

After disabling SIP, the vagrant installation routine works.

You really should NOT disable SIP permanently. There's a reason for it being there!

**Comment by marek-obuchowicz** [comment]
Closing as this is vagrant/mac os topic and is solved via documentation, there's no fix to be applied on the dev vm level
