### ISSUE TITLE
Elasticsearch in docker configuration

### ISSUE THREAD

**Issue by marek-obuchowicz** [spryker/devvm#62]
https://github.com/spryker/devvm/blob/b70d207cdba6ddf804e5e0002976a655f09418c7/saltstack/base/elasticsearch/files/elasticsearch_instance/etc/elasticsearch/elasticsearch.yml#L66

@tamasnyulas do we need this is docker setup, or can we skip this setting?

**Comment by tamasnyulas** [comment]
Currently we are not using scripts, however they can be and should be available on demand for customers. A good example to use them is data driven ranking: https://project-a.github.io/on-site-search-design-patterns-for-e-commerce/#data-driven-ranking (see "function_score").
