### ISSUE TITLE
MySQL Error 1045: Access denied 

### ISSUE THREAD

**Issue by kfrohwein** [spryker/devvm#82]
I am checking the v4.0.0 and it runs into one error if I debug the salt minion with `sudo salt-call -l debug state.apply`

Seems minor thought and we use pgsql.

```
----------
ID: mysql_root_user
Function: mysql_user.present
Name: root
Result: False
Comment: MySQL Error 1045: Access denied for user 'root'@'localhost' (using password: NO)
Started: 18:56:45.167759
Duration: 17.982 ms
Changes:
```

**Comment by stanislavrussu** [comment]
Hello,
Please provide us with step-by-step instructions on how to reproduce the issue.
Thank you!
