### ISSUE TITLE
Custom VM name

### ISSUE THREAD

**Issue by marius-rizac** [spryker/devvm#9]
Latest version of VM has it's own name defined in virtual box. Would be very helpful to have configuration in Vagrantfile to change VM name, alocated memory or othere needed parameters

```ruby
config.vm.provider "virtualbox" do |vb|
    vb.name = 'Spryker Dev VM'
    # other seetings here
end
```

**Comment by marek-obuchowicz** [comment]
I assume you talk about "quick start vm", which creates default Vagrantfile?
If yes, then there are two ways to do it:
 - either edit created (default) Vagrantfile and place there options - exactly as you mentioned above. sadly "quick-start" vagrant doesn't allow us to define how the default `Vagrantfile` looks like, it comes directly from Vagrant template
 - use environmental variables while running `vagrant up` for the first time:
```
VM_CPUS=2 VM_MEMORY=8192 VM_NAME="My custom name" vagrant up
```

Please let me know if those options are fine for you, if so - i'll add it to documentation.

**Comment by hhebbo** [comment]
-i
